version: "3.9"
services:
  discovery:
    build: ../discovery-server
    ports:
      - "8761:8761"
    image: "discovery-service"
  matiere_B:
    build: ../Matiere-MicroS
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      - spring.cloud.config.uri=http://config:8888
    ports:
      - "3000:8080"
    image: "matiere-service"
    
  node_ms:
    build: ../NodeJS-Micro-Service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=discovery
      - MONGO_URI=mongodb+srv://m001-student:m001-mongodb-basics@sandbox.stloa.mongodb.net/testdata?retryWrites=true&w=majority
      - PORT=5000
      - NODE_ENV=development
    ports:
      - "5000:5000"
    image: "nodejs-micro-service"
  club_B:
    build: ../club
    environment:
     - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
     - spring.cloud.config.uri=http://config:8888
    ports:
     - "3001:8081"
    image: "club-service"
    depends_on:
     - event_A
  event_A:
      build: ../event
      environment:
       - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
       - spring.cloud.config.uri=http://config:8888
      ports:
       - "3002:8082"
      image: "event-service"
  etudiant_B:
    build: ../Etudiant-MicroS
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      - spring.cloud.config.uri=http://config:8888
    ports:
      - "3003:8083"
    image: "etudiant-service"
  gateway:
      build: ../zuul
      environment: 
        - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
        - spring.cloud.config.uri=http://config:8888
      ports:
        - "8762:8762"
      image: "gateway-server"
  config:
    build: ../configserver
    command: --spring.profiles.active=native --spring.cloud.config.server.native.searchLocations=/config
    volumes:
     - type: bind
       source: ./src/main/resources/centralRepo
       target: /config
    environment: 
     - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
     - "8888:8888"
    image: "configserver"
  
    